POST https://kinapp-api.vercel.app/api/student
Content-Type: application/json

{
"dni":"22862874",
"ingreso":"2024",
"apellido":"AAAAcom1",
"nombres":"URIEL JONATHAN DAMIáN",
"comision":"01",
"horarioComision":"Ma 08:00 a 12:00",
"cursada":"2024"
}